version: '3.4'

services:
  audio:
    image: audio
    container_name: audio
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_URL=${DB_URL}/audio_dev
      - DATABASE_TEST_URL=${DB_URL}/audio_test
    depends_on:
      - audio_db
    links:
      - audio_db
    networks:
      - backend

  audio_db:
    container_name: audio_db
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

networks:
  backend:
