"""empty message

Revision ID: 0440054220fc
Revises: 0e26a2d71475
Create Date: 2021-03-19 01:51:17.799574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0440054220fc'
down_revision = '0e26a2d71475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_book', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_book', 'duration')
    # ### end Alembic commands ###
