"""empty message

Revision ID: 0e26a2d71475
Revises: 
Create Date: 2021-03-19 00:13:23.019330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e26a2d71475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audio_book', ['id'])
    op.create_unique_constraint(None, 'podcast', ['id'])
    op.create_unique_constraint(None, 'song', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='unique')
    op.drop_constraint(None, 'podcast', type_='unique')
    op.drop_constraint(None, 'audio_book', type_='unique')
    # ### end Alembic commands ###
