"""empty message

Revision ID: 497f864ad853
Revises: 68c6aa3581bd
Create Date: 2021-03-19 03:29:51.493080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f864ad853'
down_revision = '68c6aa3581bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('guest', sa.String(length=100), nullable=True))
    op.drop_column('participant', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('participant', 'guest')
    # ### end Alembic commands ###
