"""empty message

Revision ID: 56380aa4277f
Revises: 497f864ad853
Create Date: 2021-03-19 07:21:50.962610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56380aa4277f'
down_revision = '497f864ad853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
