"""empty message

Revision ID: c30ccd7eef58
Revises: f22678b87322
Create Date: 2021-03-19 08:32:42.393205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c30ccd7eef58'
down_revision = 'f22678b87322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('participants', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'participants')
    # ### end Alembic commands ###
