"""empty message

Revision ID: f22678b87322
Revises: 56380aa4277f
Create Date: 2021-03-19 08:11:56.585419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f22678b87322'
down_revision = '56380aa4277f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('podcast_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], name='participant_podcast_id_fkey', onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
